version: "3.3"
services:
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat-system
    ports:
     - "3306:3306"
  web:
    build: .
    volumes:
      - .:/chat-system
    ports:
      - "3000:3000"
    depends_on: 
     - db
     - redis
  queue:
    image: rabbitmq:3.8-management
    ports: 
      - "15672:15672"
      - "5672:5672"
  redis:
    image: redis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    volumes:
      - elasticsearchvolume:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    environment:
      - node.name=elasticsearch
      - cluster.name=chat-message-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
volumes: 
  mysql: 
  elasticsearchvolume:
